name: CI unit test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Install dependencies"
      run: |
        sudo sed -i '/deb-src/s/^# //' /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get -y build-dep grub2
        sudo apt-get -y install texlive
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: |
        mkdir -p build-efi
        cd build-efi
        ../configure --with-platform=efi
    - name: make
    - run: make
    - name: make check
      run: make check || true
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: assets
        path: |
          ./*.log
          ./*.trs
        retention-days: 5
